### PR TITLE
[FEA] Add AsyncIterable `switchMap`

### PR DESCRIPTION
**Pull request by trxcllnt**
Add an initial AsyncIterable `switchMap` implementation.

### CODE REVIEW

**Comment by jessmorecroft** [comment]
Hi there - would love to use switchMap but no releases since this commit ... any plans for anything soon?

Cheers,
Jess

**Comment by jessmorecroft** [comment]
Awesome, cheers @trxcllnt. BTW, fantastic library.

**Comment by jessmorecroft** [comment]
> oops, thanks @jessmorecroft. forgot to release a new version.

Hi again @trxcllnt , any eta on when you might release this?

Cheers!

**Comment by trxcllnt** [comment]
I think we've been blocked by some build work we're trying to do in https://github.com/ReactiveX/IxJS/pull/341, but I'll see if I can release without it.

**Comment by trxcllnt** [comment]
@jessmorecroft published as `ix@v4.6.0` :tada:

**Comment by jessmorecroft** [comment]
Brilliant @trxcllnt , many thanks!

**Comment by trxcllnt** [comment]
@jessmorecroft just realized we also updated `flatMap` to also use the new concurrent behavior. Technically this is a breaking change, so we're re-publishing v4.6.1 with the old behavior and gonna bump to v5.0.0 with the new behavior.

**Pull request merged**
