### PR TITLE
Enable TravisCI

### PR DESCRIPTION
**Pull request by saneyuki**
This aims to enable [TravisCI](https://travis-ci.org/)

## TODO before merging into `master`

- [x] Fix all compilation errors and lint errors.
   - To enable TravisCI, I commented out all codes which causes compile errors. This approach is unwillingly, but I also think we should introduce CI once. 
- [x] Enable CI for this repository on TravisCI's dashboard

## Remained Issues

- We need to...
   - ~fix compilation errors before merging this. They might be introduced by  https://github.com/ReactiveX/IxJS/pull/11 ?~
   - ~Or we need to mark all matrix as `allow_failures` in `matrix` section.~
- The current setting allow to failure to do `npm test`. I think it should be fixed in https://github.com/ReactiveX/IxJS/issues/2

##  Related Issues

- This will fix https://github.com/ReactiveX/IxJS/issues/15
- https://github.com/ReactiveX/IxJS/issues/17

### CODE REVIEW

**Comment by saneyuki** [comment]
@mattpodwysocki 

I'd like to enable https://travis-ci.org/ for this repository. How do you think about this change?

**Comment by mattpodwysocki** [comment]
@saneyuki yes, let's do that

**Comment by saneyuki** [comment]
@mattpodwysocki 

> Enable CI for this repository on TravisCI's dashboard

Could you enable TravisCI for this repository? I don't have any permissions to do it for repositories under ReactiveX.

I think we should enable these TravisCI options:

- _Build only if .travis.yml is present_
- _Build branch updates_
- _Build pull request updates_

...And I feel it might be better for us to enable these:

- _Auto cancel branch builds_
- _Auto cancel pull request builds_

**Comment by mattpodwysocki** [comment]
@saneyuki ok, it should be now enabled

**Comment by mattpodwysocki** [comment]
@saneyuki please update the PR to reflect the name changes

**Comment by mattpodwysocki** [comment]
@saneyuki please rebase this so we can merge properly

**Comment by saneyuki** [comment]
@mattpodwysocki I'm sorry that replying is late. I'll start to rebase in this night (timezone: UTC+8)

**Comment by mattpodwysocki** [comment]
@saneyuki let me know when you are ready to merge

**Comment by saneyuki** [comment]
@mattpodwysocki I've made to enable to merge this pull request!

**Pull request merged**
