### PR TITLE
feat(rewrite): Rewrite IxJS in the style of RxJS v6

### PR DESCRIPTION
**Pull request by mattpodwysocki**
Rewrites IxJS with piped operators to allow for better composition for v3.

```typescript
// Bringing in Iterable
import { of } from 'ix/iterable';
import { map } from 'ix/iterable/operators';

const value$ = of(1, 2, 3).pipe(map(x => x * x));
for (let item of value$) {
  console.log(`Value is ${item}`);
}

// Bringing in AsyncIterable
import { of } from 'ix/asynciterable';
import { map } from 'ix/asynciterable/operators';

const value$ = of(1, 2, 3).pipe(map(x => x * x));
for await (let item of value$) {
  console.log(`Value is ${item}`);
}

// Bringing in AsyncObservable
import { of } from 'ix/asyncobservable';
import { map } from 'ix/asyncobservable/operators';

const value$ = of(1, 2, 3).pipe(map(x => x * x));
const subscription = await value$.subscribeAsync({
  next: item => console.log(`Value is ${item}`)
});

await subscription.unsubscribeAsync();
```

### CODE REVIEW

**Comment by deniszatsepin** [comment]
Hi guys, how are you doing?
Looks like there is no progress on this branch. May I help you somehow?

**Comment by trxcllnt** [comment]
Hi @deniszatsepin! Yes, the last thing I wanted to do was pull out the [existing prototype-patching methods](https://github.com/ReactiveX/IxJS/tree/master/src/add) and make an optional entrypoint that applies them all, then we should be good to go.

**Comment by deniszatsepin** [comment]
Hi @trxcllnt! Thanks for your response! May I help you somehow with that, or you just need some more time?
PS. Thank you guys, for developing such a great library. I'm going to use it in my company project for orchestrating asynchronous iterators in AWS Lambda functions.

**Comment by michaelsbradleyjr** [comment]
In: https://github.com/ReactiveX/IxJS/blob/rewrite/src/asynciterable/asynciterablex.ts#L14-L23

Would it make sense to have `projection` be `projection?`:

```ts
async forEach(
  projection?: (value: T, index: number) => void | Promise<void>,
  thisArg?: any
): Promise<void> {
  const fn = bindCallback(projection || () => {}, thisArg, 2);
  let i = 0;
  for await (let item of this) {
    await fn(item, i++);
  }
}
```

That way one can kick-start processing with an empty `.forEach()` like one can do with an empty `.subscribe()` on an Rx Observable.

```js
const {Subject} = require('rxjs');
const {tap: rxTap} = require('rxjs/operators');

const {from: ixFrom} = require('ix/asynciterable');
const {tap: ixTap} = require('ix/asynciterable/operators');

const doSideEffects = (v) => {/* ... */};

let sub = new Subject();
sub$.pipe(rxTap(doSideEffects)).subscribe();

sub = new Subject();
ixFrom(sub$).pipe(ixTap(doSideEffects)).forEach();
```

**Comment by trxcllnt** [comment]
That sounds fine with me, but I think it's meant to mirror `Array.prototype.forEach` @mattpodwysocki thoughts?

**Comment by michaelsbradleyjr** [comment]
Ah, okay.

Well if that would cause confusion, maybe there can be some other shorthand for saying *"do it"*, i.e. other than: `.forEach(() => {})`.

Maybe `.run()`?

**Comment by michaelsbradleyjr** [comment]
@mattpodwysocki (cc: @trxcllnt) would love to see the rewrite completed and merged soon, let us know if there's anything the community can do to help things along.

Also, it would be great if there was an equivalent of [rsjx.dev](https://rxjs.dev/api) for IxJS. Whatever its shortcomings, that site's search feature is an indispensable resource for exploring the concepts, relationships, and types of RxJS (even if examples are sometimes sorely lacking for a particular entry). I believe multiple folks in the fledgling Ix community would step-up to help flesh it out, but the effort would need some spearheading from this project's maintainers.

Sans the rewrite being completed (for "parity" with current Rx) and a docs site (i.e. something more than pure API docs), it can be difficult to justify to when/why IxJS complements RxJS. I find myself in that situation of late.

**Comment by michaelsbradleyjr** [comment]
We're past the 10-month mark since this PR was opened. Any hope for the rewrite to be finished and/or `AsyncObservable` (#137) to make a debut?

**Comment by trxcllnt** [comment]
Yeah I think @mattpodwysocki was going to look at it over the holidays. I've not been doing much with JS/TS the last year, but we can probably coordinate on a new release soon.

**Comment by michaelsbradleyjr** [comment]
Thanks for the feedback @trxcllnt! I just wanted to clarify: my previous comment was meant as a *"friendly inquiry"* — as someone buried with work in my "day job" open source project, I quite often fall behind (even *way* behind) on other open source projects (re: PRs, various chat app comm, etc.), i.e. no negative criticism was intended or implied. Merry Holidays, Joyful [Christmas][etc], and a very Happy New Year's to you and all involved in this project.

**Comment by trxcllnt** [comment]
@michaelsbradleyjr no worries, no offense taken. I joined the [NVIDIA RAPIDS](http://github.com/rapidsai/) team earlier this year and haven't been able context switch from Python and C++ back to JS. I just merged a few longstanding PRs into this branch, so we should be able to hit merge on this once the CI lights turn green.

**Comment by michaelsbradleyjr** [comment]
Awesome work! 🎉

**Pull request merged**
